name: Build pharos_receiver test image and run tests on it
run-name: Build pharos_receiver test image and run tests on it - started by ${{ github.actor }}
on:
  pull_request:
    types: [opened, synchronize]
    paths:
    - 'pharos_backend/pharos_receiver/**'
  workflow_dispatch:


jobs:
  build_image:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build image
        run: bash -x build.sh pharos_receiver build
      - name: Build test image and run tests
        run: bash -x pharos_backend/pharos_receiver/run_test.sh
