name: Build redis test image and run tests on it
run-name: Build redis test image and run tests on it - started by ${{ github.actor }}
on:
  pull_request:
    types: [opened, synchronize]
    paths:
    - 'docker_images/redis/**'
  workflow_dispatch:


jobs:
  build_image:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build image
        run: bash -x build.sh redis build
